export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGING_SUCCESS'
export const LOGIN_FAIL= 'LOGING_FAIL'
export const SET_AUTH_LOADING = ' SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
export const RESET_REGISTER_SUCCESS = 'RESET_REGISTER_SUCCESS'


